apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-app
  namespace: simpleregistry
  labels:
    app: registry-app
spec:
  selector:
    matchLabels:
      app: registry-app
  template:
    metadata:
      labels:
        app: registry-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "registryapp"
        dapr.io/app-port: "80"
        dapr.io/log-as-json: "true"
    spec:
      containers:
      - name: registry-app
        image: ashwin027/simpleregistryapi:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registryapp-dapr-ingress
  namespace: simpleregistry
spec:
  rules:
  - host: registry-app.internal
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: registryapp-dapr
            port:
              number: 80